spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  datasource:
    url: jdbc-secretsmanager:postgresql://si-dev-pgsql153.cayq42jmc6ys.ap-northeast-1.rds.amazonaws.com:5234
    driver-class-name: "com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver"
    username: td-nt-iac-tribeck
  config:
    import:
      - optional:application-module.yml
  main:
    # allow-bean-definition-overriding: true
   lazy-initialization: true
custom:
  app:
    message: "Application.yml default config"