spring:
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: never
  datasource:
    url: ""
    driver-class-name: ""
  config:
    import:
      - optional:application-module_dev.yml
  main:
#    allow-bean-definition-overriding: true
    lazy-initialization: true
  cloud:
    function:
      definition: method1;method2;nonArgsSupplier
custom:
  app:
    message: "Application.yml Development config"