spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  datasource:
    initialize: false
  config:
    import:
      - optional:application-module_stg.yml
  main:
#    allow-bean-definition-overriding:
    lazy-initialization: true
custom:
  app:
    message: "Application.yml Staging config"