spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  datasource:
    initialize: false
  config:
    import:
      - optional:application-module.yml
  main:
    # allow-bean-definition-overriding: true
   lazy-initialization: true
custom:
  app:
    message: "Application.yml default config"