spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  datasource:
    url: ""
    driver-class-name: ""
  config:
    import:
      - optional:application-module.yml
  main:
    # allow-bean-definition-overriding: true
   lazy-initialization: true
  cloud:
    function:
      definition: method1;method2;
custom:
  app:
    message: "Application.yml default config"